# Generated by Django 3.0.2 on 2020-01-06 00:32

from django.db import migrations, models
import reactransition.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reactransition.models.Photo.get_image_path)),
            ],
        ),
    ]
